# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('avatar', models.ImageField(blank=True, upload_to='projects/avatars/%Y/%m/', verbose_name='avatar')),
            ],
        ),
    ]
